### ISSUE TITLE
coud we make a video de-rushing tool ?

### ISSUE THREAD

**Issue by papiche** [antiboredom/ffmpeg-explorer#14]
to cut a video into pieces, i keep or drop

**Comment by antiboredom** [comment]
Hi - I’m not sure I understand? Can you clarify what you mean?

**Comment by papiche** [comment]
I would like to extract choosen video sequences

**Comment by antiboredom** [comment]
I'm still not sure if I understand, but you can use the trim and atrim filter to extract portions of clips.
