### ISSUE TITLE
Violence in demo videos

### ISSUE THREAD

**Issue by chrisn** [antiboredom/ffmpeg-explorer#3]
Both demo videos include violent behavior, which may cause offense, and also both detracts and distracts from the otherwise good aspects of this project. I suggest replacing these with non-violent content.

**Comment by petecooper** [comment]
Perhaps https://en.wikipedia.org/wiki/Big_Buck_Bunny might be a safer alternative.

**Comment by headscale69** [comment]
The second video is fine, IMO. I found it to be nostalgic

**Comment by systemcrash** [comment]
Hitting Nazis is not violence - it is a public service.

**Comment by erdii** [comment]
Violence against humans is always violence against humans.
If you start defining certain persons as "not human enough" to avoid calling it violence against humans then you may be employing fascist tactics.

**Comment by kddlb** [comment]
Issue author works for the BBC, which is the epitome of right-leaning "centrism."

**Comment by jubalfh** [comment]
just for the record, punching nazis is a civic virtue

**Comment by okdistribute** [comment]
We fought a war about this and the nazis did not win

**Comment by lyda** [comment]
> Violence against humans is always violence against humans.
> If you start defining certain persons as "not human enough" to avoid calling it violence against humans then you may be employing fascist tactics.

The "Greatest Generation" got their name by literally killing fascists. Sit back down son.
