### ISSUE TITLE
Aborted() message in log is confusing

### ISSUE THREAD

**Issue by dhasenan** [antiboredom/ffmpeg-explorer#5]
If possible, changing it to say whether the render was successful or not would be more user friendly.

**Comment by antiboredom** [comment]
For some reason it always says "Aborted()" at the end! I might just manually remove that message. Although also thinking of replacing the log with just a progress bar and success/failure+error message.

**Comment by antiboredom** [comment]
ok! I have changed the log to only show error messages, and added a progress indicator. @dhasenan let me know if this feels better to you now.
