### ISSUE TITLE
Values for different instances of the same filter cannot be edited separately

### ISSUE THREAD

**Issue by Azenet** [antiboredom/ffmpeg-explorer#6]
When adding 2 instances of the same effect, the values edit both instances of the effect, ignoring which one has been selected.

**Comment by antiboredom** [comment]
Thanks for posting this! I think it's a regression I introduced recently but need a sec to figure out where it's coming from...

**Comment by antiboredom** [comment]
ok - should be fixed now - I just forgot to deep clone the initial filter parameters!
